In [7]:
import numpy as np
import math 

X = np.array([ [0,0], [0,1], [1,0], [1,1] ] )
# print("AND gate")
# y = np.array( [0, 0, 0, 1] )  #AND gate
# print("OR gate")
# y = np.array( [0, 1, 1, 1] )  #OR gate
print("XOR gate")
y = np.array( [0, 1, 1, 0] )  #XOR gate
w = np.array( [0, 0, 0] )
check = True
count=0
print("weight at each steps:")

while(True):
    last_w == w
    if(not check or count == 3):
        break
    check = False
    for i in range(4):
        x = np.array([1])
        x = np.append(x, X[i], axis = 0)
        wx = np.dot(w,x)
        #assign the class which the data set's belong 
        if(wx > 0):     #class positive
            if(y[i] < 1):
                check = True
                w=np.subtract(w,x)
        else:  #class negative
            if(y[i] >0 ):
                check = True
                w=np.add(w,x)
    
    if np.all(last_w == w):
        count+=1
    else:
        count = 0
    print(w)
    

w_norm = (np.power(w,2))
w_norm = math.sqrt(w_norm[0]+w_norm[1]+w_norm[2])
x_norm = np.array([1, math.sqrt(2), math.sqrt(2), math.sqrt(3)])
if(count >= 3):
    print("can't be use preceptron training algorithm")
else:
    for i in range(4):
        x = np.array([1])
        x = np.append(x, X[i], axis = 0)
        angle = np.arccos( np.dot(w,x) / (w_norm*x_norm[i]) ) *180/math.pi
        print("the angle between the weight and input vector" + str(x) + " is " + str(angle) + "  degree",end = '\n')


XOR gate
weight at each steps:
[ 0 -1  0]
[ 1 -1  0]
[ 1 -1  0]
[ 1 -1  0]
can't be use preceptron training algorithm
